### ISSUE TITLE
wild video infer too slow

### ISSUE THREAD

**Issue by Ared521** [fan23j/yolov5-vitpose-video-annotator#3]
Hello, I have seen you from the issues of motionbert. Now I am using your warehouse to obtain json data, but the speed is very slow when I reason my own video on motionbert, 10s video takes more than ten minutes, and there are some warning messages, may I ask why?

MAGEIO FFMPEG_WRITER WARNING:  input image is not divisible by macro_block_size=16, resizing from (923, 924) to (928,  928) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisib

le by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).

0% | ▋ | 1/296 [00:00 & lt; 04:16, 1.15 it/s] [

swscaler @ 000001df1adc4300] Warning: data is not aligned!  This can lead to a speed loss

My testloader Settings are as follows: testloader_params = {

'batch_size': 1,

'shuffle': False,

'num_workers': 0,

'pin_memory': True,

'prefetch_factor': 2,

'persistent_workers': False,

'drop_last': False

}

**Comment by fan23j** [comment]
Left a comment on the original repo. Unfortunately, I did not explore the issue further and can only provide my own speculations.
