### ISSUE TITLE
support onnx/tensorrt

### ISSUE THREAD

**Issue by wanghlsara** [fan23j/yolov5-vitpose-video-annotator#5]
Hi, 
I have another question for you.
Your ViTPose with Halpe [model](https://drive.google.com/file/d/1Ylv9vojQkgpDvYcK6f2BQpyq9vnpR0ve/view?usp=share_link) works well with Pytorch. I  sucessfully exported some official vitpose models to onnx/tensorrt file by mmdeploy(command is like [this](https://github.com/open-mmlab/mmdeploy/issues/2289)),  but I don't know how to export from your Haple model. Could you share me some more infomation about your Halpe model?

**Comment by fan23j** [comment]
since i developed from the ViTPose repo, the export script should work. If you provide the config file with the weights, I believe it should work. Unless you already ran into an error?

**Comment by wanghlsara** [comment]
Thanks a lot for your reply.
I finally exported your halpe .pth model to tensorrt  .engine file and it can infer very well now.
I will close this issue, and maybe ask for your help with training techniques  in the future.
