### ISSUE TITLE
NameError: name 'init_detector' is not defined

### ISSUE THREAD

**Issue by herochen7372** [fan23j/yolov5-vitpose-video-annotator#7]
Could you help me？
![image](https://github.com/fan23j/yolov5-vitpose-video-annotator/assets/97960617/f02b3f42-1109-4b38-ab7a-23c433cdd7fd)

**Comment by fan23j** [comment]
Can you provide additional details on what you ran? The filepaths i see on the error do not point to anything in this repo it seems.
